apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
  labels:
    app: resources-demo
spec:
  containers:
    - name: app
      image: nginx:1.27
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
