[web]
web-server ansible_host=54.162.0.63

[db]
db-server ansible_host=3.93.80.179

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/ansible-lab-key
; ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3
