apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: httpd
    environment: dev
    team: devops
spec:
  containers:
    - name: httpd
      image: httpd:latest
      ports:
        - containerPort: 80
